version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9002"
    ports:
      - "9001:9000"   # API
      - "9002:9002"   # Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
